### ISSUE TITLE
Update to marked > 0.6.2 for vulnerability

### ISSUE THREAD

**Issue by rajsite** [tcort/markdown-link-extractor#5]
There was a vulnerability reported in the version of marked this package relies on here: https://www.npmjs.com/advisories/812

Would it be possible to bump the marked dependency to a version that does not have this advisory notice?

**Comment by tcort** [comment]
The pull request has been merged and a new version has been published... `1.2.1`

**Comment by Chaphasilor** [comment]
There's a new one: https://npmjs.com/advisories/1623

Looking at the [changelog for marked@2.0.0](https://github.com/markedjs/marked/releases/tag/v2.0.0), it seems like a version bump is all that's needed

@tcort what do you think? version bump and be done with it? :)
