### ISSUE TITLE
Does not extract URLs from HTML

### ISSUE THREAD

**Issue by gajus** [tcort/markdown-link-extractor#7]
HTML hyperlink can be part of markdown.

It would be nice to handle cases such as:

```markdown
<a href='http://foo.bar'>foo</b>

```

Expected:

```json
[
  "http://foo.bar"
]

```

**Comment by NicolasMassart** [comment]
Maybe this one on markedjs/marked#1723 could be related to our issue and fix it once solved in Marked.js

**Comment by tcort** [comment]
fixed in v3.0.0
